	[embeddiumextras.general]
		#Configure FPS Display mode
		#Complete mode gives you min FPS count and average count
		#Allowed Values: OFF, SIMPLE, ADVANCED
		fpsDisplay = "SIMPLE"
		#Configure FPS Display gravity
		#Places counter on specified corner of your screen
		#Allowed Values: LEFT, CENTER, RIGHT
		fpsDisplayGravity = "CENTER"
		#Configure FPS Display margin
		#Give some space between corner and text
		# Default: 12
		# Range: 0 ~ 48
		fpsDisplayMargin = 12
