name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v2.0.0.0-test4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa55bfcd960d60d6aa932dd1b6cea555f38f206462aa50acef03f59f6a38f66c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.242"
